### PR TITLE
Some organization and fix a menu bug

### PR DESCRIPTION
**Pull request by FayneAldan**
Be aware I HAVE not tested this due to not having citrus, so you'll probably want to test this before accepting this.

### CODE REVIEW

**Comment by FayneAldan** [comment]
By the way, how DO I actually compile this? I get an error trying to compile citrus because 3ds.h doesn't exist (even though I have devkitPro installed).

**Comment by FayneAldan** [comment]
Sorry. I made one mistake that I failed to throw in before the merge. The ` - 1` should be removed near the end of line 12 of gbsplayer.cpp, since I didn't notice it was already decreased by 1 in romfile.cpp. 

I actually figured out how to compile the code, but it required updating ctrulib and changing some of citrus' code because of smealum/ctrulib@11a5001f3321ce0deb62d79abfb62ac2ab54763a. Speaking of, how is citrus even supposed to compile using base_rules? I had to change it to 3ds_rules.

**Comment by Steveice10** [comment]
Both should be fixed. And it doesn't need 3ds_rules because it doesn't need to create 3dsx, smdh, or elf files, it's a library.

**Comment by FayneAldan** [comment]
Yup. The CTRULIB variable actually fixed that for me. :P

**Pull request merged**
